name: Auto Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]  # Triggers only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Webhook
        run: |
          curl -X POST "https://jodh.pythonanywhere.com/update_server" \
               -H "X-Git-Token: your_super_secret_password_123" \
               -v